server:
  port: 8090
  servlet:
    context-path: /app-carts

integrations:
  product-service:
    url: http://localhost:8080/app-core/api/v1
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
cart-service:
  cart-prefix: iMarket_cart_